"use client";

/**
 * MarkdownBody — dark-themed markdown renderer for vault note previews
 * AND now for chat messages where the inline `code` spans should act as
 * navigation hotspots.
 *
 * Shared between brain-node slide-overs and VaultBrowser's slide-over so the
 * typographic system lives in one place. Adds GFM (tables, task lists,
 * strikethrough, autolinks) and a tiny preprocessor that turns Obsidian-style
 * `[[wikilinks]]` into in-app vault links when the host provides handlers.
 *
 * Interactive code spans (Pillar add-on):
 *   - `wiki/audits/2026-05-12-sitemap.md` and other `.md` paths become
 *     clickable; the caller's `onOpenPath(path)` opens the note in a
 *     slide-over.
 *   - Bare specialist ids like `sitemap-architect` become clickable when
 *     they match the caller-supplied `knownSpecialistIds` set; the
 *     `onFocusSpecialist(id)` callback flies the camera to that desk
 *     (or opens the inbox, depending on the host).
 *   - Other inline code (severity tags like `[high]`, XML tag names like
 *     `lastmod`, raw strings) renders unchanged.
 */

import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import { type ReactNode, Fragment, memo, useMemo } from "react";

import ChartBlock, { type ChartSpec } from "@/components/vault/ChartBlock";
import { reportApiPath } from "@/lib/reports/url";

/** `[[Note Name]]` or `[[Note Name|alias]]` -> clickable vault link. */
function preprocessWikilinks(src: string): string {
  return src.replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_, target, alias) => {
    const rawTarget = target.trim();
    const display = (alias ?? rawTarget.split("#", 1)[0]).trim();
    const safeDisplay = display.replace(/\\/g, "\\\\").replace(/]/g, "\\]");
    return `[${safeDisplay}](vault:${encodeURIComponent(rawTarget)})`;
  });
}

/* -------------------------------------------------------------------------- */
/* clickable detection                                                         */
/* -------------------------------------------------------------------------- */

type ClickTarget =
  | { kind: "note"; path: string }
  | { kind: "folder"; path: string }
  | { kind: "report"; path: string; href: string }
  | { kind: "specialist"; id: string };

type InlineStatus =
  | "spawning"
  | "queued"
  | "running"
  | "reviewing"
  | "complete"
  | "succeeded"
  | "failed"
  | "skipped"
  | "cancelled"
  | "dispatched";

const INLINE_STATUS_STYLES: Record<InlineStatus, string> = {
  spawning: "border-orange-500/50 bg-orange-500/15 text-orange-200 animate-pulse",
  queued: "border-amber-500/50 bg-amber-500/15 text-amber-200",
  running: "border-orange-500/50 bg-orange-500/15 text-orange-200 animate-pulse",
  reviewing: "border-sky-400/50 bg-sky-500/15 text-sky-200",
  complete: "border-emerald-500/50 bg-emerald-500/15 text-emerald-200",
  succeeded: "border-emerald-500/50 bg-emerald-500/15 text-emerald-200",
  failed: "border-red-500/50 bg-red-500/15 text-red-200",
  skipped: "border-stone-500/50 bg-stone-500/15 text-stone-200",
  cancelled: "border-stone-500/50 bg-stone-500/15 text-stone-200",
  dispatched: "border-amber-500/40 bg-amber-500/10 text-amber-200",
};

function inlineStatusFor(text: string): InlineStatus | null {
  const t = text.trim().toLowerCase();
  if (t in INLINE_STATUS_STYLES) return t as InlineStatus;
  return null;
}

/** Extract plain text from a React-Markdown `code` element's `children`.
 *  `code` may contain nested nodes when GFM autolinks fire, so we walk. */
function extractText(children: ReactNode): string {
  if (typeof children === "string") return children;
  if (typeof children === "number") return String(children);
  if (Array.isArray(children)) return children.map(extractText).join("");
  if (
    children &&
    typeof children === "object" &&
    "props" in children &&
    children.props &&
    typeof children.props === "object" &&
    "children" in children.props
  ) {
    return extractText((children.props as { children: ReactNode }).children);
  }
  return "";
}

function stripTokenPunctuation(text: string): { core: string; suffix: string } {
  const match = text.match(/^(.+?)([),.;:!?]+)?$/);
  return {
    core: (match?.[1] ?? text).trim(),
    suffix: match?.[2] ?? "",
  };
}

/** Decide whether a piece of inline-code text should be made interactive. */
function detectClickTarget(
  text: string,
  knownSpecialistIds: ReadonlySet<string>,
  clientSlug?: string,
): ClickTarget | null {
  const t = text.trim().replace(/^["'`]+|["'`]+$/g, "");
  if (!t) return null;

  // Report path generated by specialists. Keep these in-app instead of
  // opening a naked API route/new tab.
  if (clientSlug && /^reports\/.+\.html$/i.test(t)) {
    return { kind: "report", path: t, href: reportApiPath(clientSlug, t) };
  }
  // Vault markdown path (relative to vault root). Allow spaces and
  // placeholder braces because template files can literally be named
  // `wiki/entities/{{site_brand}}.md`.
  if (/^wiki\/.+\.md$/i.test(t)) {
    return { kind: "note", path: t };
  }
  // Bare markdown file — resolve under wiki/ first, then the note API can
  // search by basename if it lives in a nested folder.
  if (/^[^/\\]+\.md$/i.test(t)) {
    return { kind: "note", path: `wiki/${t}` };
  }
  // Vault folder (no extension, has a slash, starts at wiki/).
  if (/^wiki\/.+\/?$/.test(t) && !/\.[a-z0-9]+$/i.test(t)) {
    return { kind: "folder", path: t.replace(/\/$/, "") };
  }
  // Specialist id — must be in the known set so we don't promote
  // random kebab-case strings.
  if (knownSpecialistIds.has(t)) {
    return { kind: "specialist", id: t };
  }
  return null;
}

const SPECIALIST_CHIP_STYLES = [
  "border-[#8a9a5b]/55 bg-[#8a9a5b]/15 text-[#dfe8c7] hover:bg-[#8a9a5b]/22",
  "border-[#6f8f7a]/55 bg-[#6f8f7a]/15 text-[#d9e8df] hover:bg-[#6f8f7a]/22",
  "border-[#9b8965]/55 bg-[#9b8965]/15 text-[#eadfcb] hover:bg-[#9b8965]/22",
  "border-[#7f89a6]/55 bg-[#7f89a6]/15 text-[#dde2f2] hover:bg-[#7f89a6]/22",
  "border-[#9b7f8f]/55 bg-[#9b7f8f]/15 text-[#ecdce5] hover:bg-[#9b7f8f]/22",
] as const;

function hashText(text: string): number {
  let hash = 0;
  for (let i = 0; i < text.length; i++) {
    hash = (hash * 31 + text.charCodeAt(i)) >>> 0;
  }
  return hash;
}

function specialistChipClass(id: string): string {
  return SPECIALIST_CHIP_STYLES[hashText(id) % SPECIALIST_CHIP_STYLES.length];
}

function renderTargetButton(
  target: ClickTarget,
  display: ReactNode,
  opts: MarkdownOptions,
  key?: string,
) {
  if (target.kind === "specialist") {
    if (!opts.onFocusSpecialist) return display;
    return (
      <button
        key={key}
        type="button"
        onClick={() => opts.onFocusSpecialist?.(target.id)}
        title={`Focus ${target.id} specialist`}
        className={
          "inline-flex max-w-full items-center border px-1.5 py-0.5 align-baseline font-mono text-[11px] leading-4 transition-colors " +
          specialistChipClass(target.id)
        }
      >
        <span className="truncate">{display}</span>
      </button>
    );
  }

  if (target.kind === "report") {
    if (!opts.onOpenReport) return display;
    return (
      <button
        key={key}
        type="button"
        onClick={() => opts.onOpenReport?.(target.href, target.path)}
        title={`Open report ${target.path}`}
        className="inline-flex max-w-full cursor-pointer items-center border border-gold/50 bg-gold/10 px-1.5 py-0.5 align-baseline font-mono text-[12px] leading-4 text-gold underline decoration-gold/30 underline-offset-2 transition-colors hover:border-gold hover:bg-gold/20 hover:decoration-gold"
      >
        <span className="truncate">{display}</span>
      </button>
    );
  }

  if (!opts.onOpenPath) return display;
  return (
    <button
      key={key}
      type="button"
      onClick={() => opts.onOpenPath?.(target.path, target.kind)}
      title={target.kind === "folder" ? `Open folder ${target.path}` : `Open ${target.path}`}
      className="inline-flex max-w-full cursor-pointer items-center border border-gold/40 bg-charcoal px-1 py-0.5 align-baseline font-mono text-[12px] leading-4 text-gold underline decoration-gold/30 underline-offset-2 transition-colors hover:border-gold hover:bg-gold/15 hover:decoration-gold"
    >
      <span className="truncate">{display}</span>
    </button>
  );
}

const INLINE_TOKEN_RE =
  /(wiki\/[^\s`<>()\]]+|reports\/[^\s`<>()\]]+|[A-Za-z0-9_.{}-]+\.md|[A-Za-z0-9][A-Za-z0-9_-]{2,})/g;

function renderInlineText(text: string, opts: MarkdownOptions): ReactNode {
  const pieces: ReactNode[] = [];
  let lastIndex = 0;
  for (const match of text.matchAll(INLINE_TOKEN_RE)) {
    const raw = match[0];
    const index = match.index ?? 0;
    if (index > lastIndex) pieces.push(text.slice(lastIndex, index));
    const { core, suffix } = stripTokenPunctuation(raw);
    const target = detectClickTarget(core, opts.knownSpecialistIds, opts.clientSlug);
    if (target) {
      pieces.push(renderTargetButton(target, core, opts, `target-${index}-${core}`));
      if (suffix) pieces.push(suffix);
    } else {
      pieces.push(raw);
    }
    lastIndex = index + raw.length;
  }
  if (lastIndex < text.length) pieces.push(text.slice(lastIndex));
  return pieces.length > 0 ? pieces : text;
}

function renderInlineChildren(children: ReactNode, opts: MarkdownOptions): ReactNode {
  if (typeof children === "string") return renderInlineText(children, opts);
  if (typeof children === "number") return children;
  if (Array.isArray(children)) {
    return children.map((child, index) => (
      <Fragment key={index}>{renderInlineChildren(child, opts)}</Fragment>
    ));
  }
  return children;
}

/* -------------------------------------------------------------------------- */
/* renderer                                                                    */
/* -------------------------------------------------------------------------- */

interface MarkdownOptions {
  onOpenPath?: (path: string, kind: "note" | "folder") => void;
  onOpenReport?: (href: string, label?: string) => void;
  onFocusSpecialist?: (id: string) => void;
  knownSpecialistIds: ReadonlySet<string>;
  /** Required for chart blocks that reference a `.data.json` sidecar. When
   *  omitted, ref-based charts fall back to a placeholder. */
  clientSlug?: string;
  notePath?: string;
}

function buildComponents(opts: MarkdownOptions): Components {
  const isReportHref = (href?: string) =>
    Boolean(href?.startsWith("/api/clients/") && href.includes("/reports/"));
  const relativeReportHref = (href?: string) => {
    if (!href || !opts.clientSlug) return null;
    const normalized = href.replace(/^\.\/+/, "");
    if (!/^reports\/.+\.html$/i.test(normalized)) return null;
    return {
      path: normalized,
      href: reportApiPath(opts.clientSlug, normalized),
    };
  };
  const opensAwayFromApp = (href?: string) =>
    Boolean(href?.startsWith("http"));

  return {
  h1: (props) => (
    <h1
      className="mt-6 mb-3 text-base font-medium uppercase tracking-tight text-white"
      {...props}
    />
  ),
  h2: (props) => (
    <h2
      className="mt-5 mb-2 text-[13px] font-medium uppercase tracking-[0.18em] text-white"
      {...props}
    />
  ),
  h3: (props) => (
    <h3
      className="mt-4 mb-1.5 text-[11px] uppercase tracking-[0.2em] text-ash"
      {...props}
    />
  ),
  h4: (props) => (
    <h4 className="mt-3 mb-1 text-[11px] uppercase tracking-wider text-ash" {...props} />
  ),
  p: ({ children, ...props }) => (
    <p className="my-2 text-[13px] leading-6 text-white/85" {...props}>
      {renderInlineChildren(children, opts)}
    </p>
  ),
  ul: (props) => (
    <ul className="my-2 ml-5 list-disc space-y-1 marker:text-ash/60" {...props} />
  ),
  ol: (props) => (
    <ol className="my-2 ml-5 list-decimal space-y-1 marker:text-ash/60" {...props} />
  ),
  li: ({ children, ...props }) => (
    <li className="text-[13px] leading-6 text-white/85" {...props}>
      {renderInlineChildren(children, opts)}
    </li>
  ),
  a: ({ href, children, ...props }) => {
    if (href?.startsWith("vault:")) {
      const rawTarget = decodeURIComponent(href.slice("vault:".length));
      const target = rawTarget.endsWith("/")
        ? { kind: "folder" as const, path: rawTarget.replace(/\/$/, "") }
        : { kind: "note" as const, path: rawTarget };
      if (opts.onOpenPath) {
        return renderTargetButton(target, children, opts);
      }
      return <strong className="font-semibold text-white">{children}</strong>;
    }
    const reportHref = relativeReportHref(href);
    if ((isReportHref(href) || reportHref) && opts.onOpenReport) {
      const label = extractText(children) || "Open report";
      return (
        <button
          type="button"
          onClick={() => opts.onOpenReport?.(reportHref?.href ?? href!, label)}
          className="border border-gold/50 bg-gold/10 px-1.5 py-0.5 font-mono text-[12px] text-gold underline decoration-gold/30 underline-offset-2 transition-colors hover:border-gold hover:bg-gold/20"
          title={reportHref?.path ?? label}
        >
          {children}
        </button>
      );
    }
    const openInNewTab = opensAwayFromApp(href);
    return (
      <a
        href={href}
        target={openInNewTab ? "_blank" : undefined}
        rel={openInNewTab ? "noopener noreferrer" : undefined}
        className="text-gold underline decoration-gold/40 underline-offset-2 hover:decoration-gold"
        {...props}
      >
        {children}
      </a>
    );
  },
  strong: ({ children, ...props }) => (
    <strong className="font-semibold text-white" {...props}>
      {renderInlineChildren(children, opts)}
    </strong>
  ),
  em: ({ children, ...props }) => (
    <em className="italic text-white/90" {...props}>
      {renderInlineChildren(children, opts)}
    </em>
  ),
  hr: () => <hr className="my-4 border-t border-graphite" />,
  blockquote: ({ children, ...props }) => (
    <blockquote
      className="my-3 border-l-2 border-graphite pl-3 text-[13px] italic text-ash"
      {...props}
    >
      {renderInlineChildren(children, opts)}
    </blockquote>
  ),
  pre: (props) => {
    // Recognise a ```chart fenced block by peeking at the language tag of
    // the wrapped <code>. When we have it, render an inline SVG chart
    // instead of the raw code chrome. The block JSON is the textContent
    // of the <code>; parse-or-fallback so a malformed spec still renders
    // its source rather than crashing the slide-over.
    const child = (props.children as { props?: { className?: string; children?: ReactNode } } | undefined)?.props;
    const language = child?.className ?? "";
    const isChart = /language-chart\b/.test(language);
    if (isChart && opts.clientSlug && opts.notePath) {
      const text = extractText(child?.children).trim();
      try {
        const spec = JSON.parse(text) as ChartSpec;
        return (
          <ChartBlock
            spec={spec}
            clientSlug={opts.clientSlug}
            notePath={opts.notePath}
          />
        );
      } catch {
        /* fall through to default <pre> rendering so the user can still
         * read the (broken) spec rather than seeing nothing. */
      }
    }
    return (
      <pre
        className="my-3 overflow-x-auto border border-graphite bg-charcoal p-3 text-[12px] leading-5 text-white/90"
        {...props}
      />
    );
  },
  code: ({ className, children, ...rest }) => {
    const isBlock = /language-/.test(className ?? "");
    if (isBlock) {
      // Inside <pre>; let <pre> own the chrome.
      return (
        <code className={`font-mono ${className ?? ""}`} {...rest}>
          {children}
        </code>
      );
    }

    // Inline code: try to promote to a clickable hotspot.
    const text = extractText(children);
    const status = inlineStatusFor(text);
    if (status) {
      return (
        <span
          className={
            "inline-flex items-center border px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider " +
            INLINE_STATUS_STYLES[status]
          }
        >
          {status}
        </span>
      );
    }
    const target = detectClickTarget(text, opts.knownSpecialistIds, opts.clientSlug);

    if (target) {
      // Only render the interactive shell when a handler exists; otherwise
      // we'd offer a click that does nothing.
      const interactive =
        target.kind === "specialist"
          ? Boolean(opts.onFocusSpecialist)
          : target.kind === "report"
            ? Boolean(opts.onOpenReport)
          : Boolean(opts.onOpenPath);
      if (interactive) {
        return renderTargetButton(target, children, opts);
      }
    }

    return (
      <code
        className="border border-graphite bg-charcoal px-1 py-0.5 font-mono text-[12px] text-gold"
        {...rest}
      >
        {children}
      </code>
    );
  },
  table: (props) => (
    <div className="my-3 overflow-x-auto border border-graphite">
      <table className="w-full border-collapse text-[12px]" {...props} />
    </div>
  ),
  thead: (props) => <thead className="bg-iron" {...props} />,
  th: (props) => (
    <th
      className="border-b border-graphite px-2 py-1.5 text-left text-[10px] font-medium uppercase tracking-wider text-ash"
      {...props}
    />
  ),
  td: ({ children, ...props }) => (
    <td className="border-b border-graphite/50 px-2 py-1.5 text-[12px] text-white/85" {...props}>
      {renderInlineChildren(children, opts)}
    </td>
  ),
  // remark-gfm task list checkboxes
  input: (props) => {
    if (props.type === "checkbox") {
      return (
        <input
          {...props}
          disabled
          className="mr-2 inline-block accent-gold"
          style={{ transform: "translateY(1px)" }}
        />
      );
    }
    return <input {...props} />;
  },
  };
}

const EMPTY_SPECIALIST_SET: ReadonlySet<string> = new Set();

interface Props {
  source: string;
  /** Caller for vault path clicks. When omitted, paths render as plain
   *  inline code (no button). */
  onOpenPath?: (path: string, kind: "note" | "folder") => void;
  onOpenReport?: (href: string, label?: string) => void;
  /** Caller for specialist-id clicks. When omitted, ids render as plain
   *  inline code. Requires `knownSpecialistIds` to be non-empty. */
  onFocusSpecialist?: (id: string) => void;
  /** The set of valid specialist ids. Passed by the chat layer so we
   *  don't promote unrelated kebab-case strings into clickable hotspots. */
  knownSpecialistIds?: ReadonlySet<string> | ReadonlyArray<string>;
  /** Required for `chart` fenced blocks that reference a `.data.json`
   *  sidecar via `ref`. When omitted, ref-based charts fall back to the
   *  default `<pre>` rendering of the code block. */
  clientSlug?: string;
  notePath?: string;
}

function MarkdownBodyImpl({
  source,
  onOpenPath,
  onOpenReport,
  onFocusSpecialist,
  knownSpecialistIds,
  clientSlug,
  notePath,
}: Props) {
  const processed = useMemo(() => preprocessWikilinks(source), [source]);
  const idSet = useMemo<ReadonlySet<string>>(() => {
    if (!knownSpecialistIds) return EMPTY_SPECIALIST_SET;
    return knownSpecialistIds instanceof Set
      ? knownSpecialistIds
      : new Set(knownSpecialistIds);
  }, [knownSpecialistIds]);
  const components = useMemo(
    () =>
      buildComponents({
        onOpenPath,
        onOpenReport,
        onFocusSpecialist,
        knownSpecialistIds: idSet,
        clientSlug,
        notePath,
      }),
    [onOpenPath, onOpenReport, onFocusSpecialist, idSet, clientSlug, notePath],
  );
  return (
    <div
      className="markdown-body min-w-0"
      style={{
        // Hard break-word so long URLs / unbreakable strings can't escape
        // the container left/right edges. Inline chip buttons also respect
        // this via their own max-w-full. Combined with `min-w-0` this kills
        // the overflow bleed seen when the host is a constrained flex/grid
        // cell (e.g. an OS window body).
        overflowWrap: "anywhere",
        wordBreak: "break-word",
      }}
    >
      <ReactMarkdown remarkPlugins={[remarkGfm]} components={components}>
        {processed}
      </ReactMarkdown>
    </div>
  );
}

/**
 * THE click-lag fix. Without this memo, every ChatPanel re-render (focus
 * change, hover change, tab switch, stream tick, ANY state movement
 * upstream) cascaded through every chat turn: each turn's MarkdownBody
 * re-executed react-markdown's full parse + AST walk, even though the
 * turn's `source` string hadn't changed.
 *
 * For an orchestrator chat with ~100 turns, that meant **100 markdown
 * parses on every click** — the dominant source of perceived lag.
 *
 * Default shallow equality is correct here because ChatPanel feeds
 * stable identities to every prop:
 *   - `source`         — string, compared by value
 *   - `onOpenPath`     — `useCallback([], [])` in ChatPanel → stable
 *   - `onOpenReport`   — `useCallback` stable
 *   - `onFocusSpecialist` — `useCallback` stable
 *   - `knownSpecialistIds` — `useMemo` on `[targets]` → stable across most renders
 *   - `clientSlug`, `notePath` — strings, compared by value
 *
 * Net effect: a click that doesn't change any turn's source produces
 * zero markdown re-parses. Click-lag collapses from O(turns) to O(1).
 */
const MarkdownBody = memo(MarkdownBodyImpl);

export default MarkdownBody;
