"use client";

import { useEffect, useState } from "react";
import MarkdownBody from "@/components/MarkdownBody";
import { AudioView } from "@/components/os/viewers/AudioView";
import { VideoView } from "@/components/os/viewers/VideoView";
import { DocxView } from "@/components/os/viewers/DocxView";
import { XlsxView } from "@/components/os/viewers/XlsxView";
import { ZipView } from "@/components/os/viewers/ZipView";

/**
 * Polymorphic file viewer.
 *
 * The same `NoteWindow` powers the OS window kind `"note"` for every file
 * type we know how to display, plus external URLs:
 *
 *   - `.md` / `.markdown`        → JSON note API + MarkdownBody (frontmatter
 *                                  + body + clickable wikilinks + chart
 *                                  blocks).
 *   - `.txt` / `.log` / `.csv` / `.json` / `.yaml` / `.xml` / `.svg`
 *                                → raw file API, rendered inside a <pre>.
 *   - `.html` / `.htm`            → raw file API, rendered inside a sandboxed
 *                                  <iframe srcDoc>.
 *   - `.pdf`                      → raw file API, iframe (browser-native
 *                                  PDF viewer).
 *   - `.png`/`.jpg`/`.webp`/etc.  → raw file API, plain <img>.
 *   - `http(s)://…` paths         → external <iframe> sandbox (limited; many
 *                                  sites refuse to be framed via CSP).
 *
 * `path` is the vault-relative file path OR an absolute http(s) URL.
 */

interface NotePayload {
  ok: boolean;
  path: string;
  frontmatter: Record<string, unknown>;
  body: string;
  links?: {
    outgoing: Array<{ path: string; title: string; target: string }>;
    backlinks: Array<{ path: string; title: string; target: string }>;
    unresolved: Array<{ target: string }>;
  };
}

interface NoteWindowProps {
  clientSlug?: string;
  path?: string;
  approvalStatus?: string;
}

type Kind =
  | "external-url"
  | "markdown"
  | "text"
  | "html"
  | "pdf"
  | "image"
  | "audio"
  | "video"
  | "docx"
  | "doc-legacy"
  | "xlsx"
  | "zip"
  | "unknown";

const AUDIO_EXTS = new Set([".mp3", ".wav", ".ogg", ".oga", ".m4a", ".aac", ".flac"]);
const VIDEO_EXTS = new Set([".mp4", ".m4v", ".webm", ".mov"]);
const TEXT_EXTS = new Set([
  ".txt", ".log", ".csv", ".tsv", ".json", ".yaml", ".yml", ".xml", ".svg",
]);
const IMAGE_EXTS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif"]);
const ZIP_EXTS = new Set([".zip"]);

function detectKind(p: string): Kind {
  // Absolute URLs and same-origin API paths (e.g. /api/clients/.../reports/...
  // generated by the report-renderer) both render via the iframe view.
  if (/^(\/api\/|https?:\/\/)/i.test(p)) return "external-url";
  const ext = (p.match(/\.[a-z0-9]+$/i)?.[0] ?? "").toLowerCase();
  if (ext === ".md" || ext === ".markdown") return "markdown";
  if (TEXT_EXTS.has(ext)) return "text";
  if (ext === ".html" || ext === ".htm") return "html";
  if (ext === ".pdf") return "pdf";
  if (IMAGE_EXTS.has(ext)) return "image";
  if (AUDIO_EXTS.has(ext)) return "audio";
  if (VIDEO_EXTS.has(ext)) return "video";
  if (ext === ".docx") return "docx";
  if (ext === ".doc") return "doc-legacy";
  if (ext === ".xlsx" || ext === ".xls") return "xlsx";
  if (ZIP_EXTS.has(ext)) return "zip";
  return "unknown";
}

function fileApiUrl(slug: string, p: string): string {
  return `/api/brain/file?slug=${encodeURIComponent(slug)}&path=${encodeURIComponent(p)}`;
}

const containerStyle: React.CSSProperties = {
  height: "100%",
  width: "100%",
  overflow: "hidden",
  fontFamily: "var(--font-ui)",
  fontSize: 12.5,
  color: "var(--fg)",
};

const stateStyle: React.CSSProperties = {
  padding: 16,
  fontFamily: "var(--font-ui)",
  fontSize: 12,
};

export function NoteWindow({ clientSlug, path }: NoteWindowProps) {
  if (!path) {
    return (
      <div style={{ ...stateStyle, color: "var(--fg-faint)" }}>
        Select a file to preview.
      </div>
    );
  }
  const kind = detectKind(path);

  if (kind === "external-url") return <ExternalUrlView url={path} />;
  if (kind === "markdown" && clientSlug) {
    return <MarkdownView clientSlug={clientSlug} path={path} />;
  }
  if (!clientSlug) {
    return (
      <div style={{ ...stateStyle, color: "var(--err)" }}>
        Missing client context.
      </div>
    );
  }
  if (kind === "text") return <TextView clientSlug={clientSlug} path={path} />;
  if (kind === "html") return <HtmlView clientSlug={clientSlug} path={path} />;
  if (kind === "pdf") return <PdfView clientSlug={clientSlug} path={path} />;
  if (kind === "image") return <ImageView clientSlug={clientSlug} path={path} />;
  if (kind === "audio") return <AudioView clientSlug={clientSlug} path={path} />;
  if (kind === "video") return <VideoView clientSlug={clientSlug} path={path} />;
  if (kind === "docx") return <DocxView clientSlug={clientSlug} path={path} />;
  if (kind === "xlsx") return <XlsxView clientSlug={clientSlug} path={path} />;
  if (kind === "zip") return <ZipView clientSlug={clientSlug} path={path} />;
  if (kind === "doc-legacy") return <DocLegacyNotice clientSlug={clientSlug} path={path} />;

  return <DownloadFallback clientSlug={clientSlug} path={path} />;
}

/* ── Legacy .doc notice ─────────────────────────────────────────────────── */

function DocLegacyNotice({ clientSlug, path }: { clientSlug: string; path: string }) {
  return (
    <div style={{ ...stateStyle, color: "var(--fg-muted)" }}>
      <p style={{ marginBottom: 8 }}>
        Legacy binary <code>.doc</code> files can&apos;t be previewed inline.
        Convert to <code>.docx</code> for an inline view, or download the
        file as-is below.
      </p>
      <a
        href={fileApiUrl(clientSlug, path)}
        target="_blank"
        rel="noopener noreferrer"
        style={{ color: "var(--accent)", textDecoration: "underline" }}
      >
        Download {path.split("/").pop()}
      </a>
    </div>
  );
}

/* ── Markdown (JSON + MarkdownBody) ─────────────────────────────────────── */

function MarkdownView({ clientSlug, path }: { clientSlug: string; path: string }) {
  const [data, setData] = useState<NotePayload | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setLoading(true);
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setError(null);
    fetch(`/api/brain/note?slug=${encodeURIComponent(clientSlug)}&path=${encodeURIComponent(path)}`)
      .then(async (res) => {
        if (cancelled) return;
        const json = await res.json();
        if (!json.ok) throw new Error(json.error ?? "Failed to load note");
        setData(json as NotePayload);
      })
      .catch((e) => { if (!cancelled) setError(String(e?.message ?? e)); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [clientSlug, path]);

  if (loading) return <div style={{ ...stateStyle, color: "var(--fg-muted)" }}>Loading…</div>;
  if (error) return <div style={{ ...stateStyle, color: "var(--err)" }}>{error}</div>;
  if (!data) return null;

  const approvalStatus = typeof data.frontmatter.approval_status === "string"
    ? data.frontmatter.approval_status
    : undefined;

  const fmBorderColor =
    approvalStatus === "needs-review" ? "var(--ribbon)"
    : approvalStatus === "approved" ? "var(--ok)"
    : approvalStatus === "rejected" ? "var(--err)"
    : "var(--chrome-border)";

  const fmLines = Object.entries(data.frontmatter)
    .filter(([k]) => k !== "brain_schema")
    .map(([k, v]) => `${k}: ${typeof v === "object" ? JSON.stringify(v) : String(v ?? "")}`)
    .join("\n");

  return (
    <div
      style={{
        ...containerStyle,
        overflowY: "auto",
        padding: "12px 16px",
      }}
    >
      {fmLines && (
        <pre style={{
          borderLeft: `3px solid ${fmBorderColor}`,
          paddingLeft: 10, marginBottom: 14,
          fontSize: 10.5,
          color: "var(--fg-muted)",
          whiteSpace: "pre-wrap", wordBreak: "break-all",
          background: "transparent",
          fontFamily: "var(--font-mono, monospace)",
        }}>
          {fmLines}
        </pre>
      )}
      <MarkdownBody source={data.body} clientSlug={clientSlug} notePath={path} />
    </div>
  );
}

/* ── Plain-text family (txt/json/csv/yaml/svg-as-source) ────────────────── */

function TextView({ clientSlug, path }: { clientSlug: string; path: string }) {
  const [body, setBody] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(fileApiUrl(clientSlug, path))
      .then(async (res) => {
        if (cancelled) return;
        if (!res.ok) {
          const j = await res.json().catch(() => null);
          throw new Error(j?.error ?? `HTTP ${res.status}`);
        }
        return res.text();
      })
      .then((text) => { if (!cancelled && text !== undefined) setBody(text); })
      .catch((e) => { if (!cancelled) setError(String(e?.message ?? e)); });
    return () => { cancelled = true; };
  }, [clientSlug, path]);

  if (error) return <div style={{ ...stateStyle, color: "var(--err)" }}>{error}</div>;
  if (body == null) return <div style={{ ...stateStyle, color: "var(--fg-muted)" }}>Loading…</div>;

  return (
    <pre
      style={{
        ...containerStyle,
        overflow: "auto",
        margin: 0,
        padding: 16,
        whiteSpace: "pre-wrap",
        wordBreak: "break-word",
        fontFamily: "var(--font-mono, ui-monospace, monospace)",
        fontSize: 12,
        lineHeight: 1.55,
        background: "transparent",
      }}
    >
      {body}
    </pre>
  );
}

/* ── HTML (sandbox iframe) ──────────────────────────────────────────────── */

function HtmlView({ clientSlug, path }: { clientSlug: string; path: string }) {
  const [doc, setDoc] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    fetch(fileApiUrl(clientSlug, path))
      .then((res) => {
        if (cancelled) return null;
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.text();
      })
      .then((text) => { if (!cancelled && text != null) setDoc(text); })
      .catch((e) => { if (!cancelled) setError(String(e?.message ?? e)); });
    return () => { cancelled = true; };
  }, [clientSlug, path]);

  if (error) return <div style={{ ...stateStyle, color: "var(--err)" }}>{error}</div>;
  if (doc == null) return <div style={{ ...stateStyle, color: "var(--fg-muted)" }}>Loading…</div>;

  return (
    <iframe
      title="HTML preview"
      srcDoc={doc}
      sandbox="allow-popups allow-popups-to-escape-sandbox"
      style={{ ...containerStyle, border: 0, background: "white" }}
    />
  );
}

/* ── PDF (browser-native viewer) ────────────────────────────────────────── */

function PdfView({ clientSlug, path }: { clientSlug: string; path: string }) {
  return (
    <iframe
      title="PDF preview"
      src={fileApiUrl(clientSlug, path)}
      style={{ ...containerStyle, border: 0, background: "var(--panel-bg)" }}
    />
  );
}

/* ── Image (PNG/JPG/WEBP/GIF) ───────────────────────────────────────────── */

function ImageView({ clientSlug, path }: { clientSlug: string; path: string }) {
  return (
    <div
      style={{
        ...containerStyle,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "var(--panel-bg-soft)",
        padding: 16,
      }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        src={fileApiUrl(clientSlug, path)}
        alt={path.split("/").pop() ?? "image"}
        style={{ maxWidth: "100%", maxHeight: "100%", objectFit: "contain" }}
      />
    </div>
  );
}

/* ── External URL (cross-origin iframe with CSP-aware fallback) ─────────── */

function ExternalUrlView({ url }: { url: string }) {
  return (
    <div style={{ ...containerStyle, display: "flex", flexDirection: "column" }}>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          gap: 8,
          padding: "6px 12px",
          borderBottom: "1px solid var(--chrome-border)",
          fontSize: 11,
          color: "var(--fg-muted)",
        }}
      >
        <span>Web preview ·</span>
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          style={{ color: "var(--accent)", textDecoration: "underline" }}
        >
          open in browser
        </a>
        <span style={{ marginLeft: "auto", color: "var(--fg-faint)" }}>
          some sites refuse to be framed (X-Frame-Options / CSP)
        </span>
      </div>
      <iframe
        title="External page"
        src={url}
        sandbox="allow-same-origin allow-scripts allow-popups allow-popups-to-escape-sandbox"
        referrerPolicy="no-referrer"
        style={{ flex: 1, border: 0, background: "white" }}
      />
    </div>
  );
}

/* ── Unknown extension fallback ─────────────────────────────────────────── */

function DownloadFallback({ clientSlug, path }: { clientSlug: string; path: string }) {
  return (
    <div style={{ ...stateStyle, color: "var(--fg-muted)" }}>
      <p style={{ marginBottom: 8 }}>
        No inline viewer for this file type.
      </p>
      <a
        href={fileApiUrl(clientSlug, path)}
        target="_blank"
        rel="noopener noreferrer"
        style={{ color: "var(--accent)", textDecoration: "underline" }}
      >
        Download {path.split("/").pop()}
      </a>
    </div>
  );
}
